services:
  planning-poker-backend:
    build: .
    environment:
      QUARKUS_PROFILE: dev
      GITLAB_URL: ${GITLAB_URL}
      GITLAB_TOKEN: ${GITLAB_TOKEN}
      JWT_PRIVATE_KEY_LOCATION: file:/run/secrets/jwt-private-key.pem
      JWT_PUBLIC_KEY_LOCATION: file:/run/secrets/jwt-public-key.pem
    volumes:
      - ${JWT_PRIVATE_KEY_FILE}:/run/secrets/jwt-private-key.pem:ro
      - ${JWT_PUBLIC_KEY_FILE}:/run/secrets/jwt-public-key.pem:ro

  planning-poker-frontend:
    build:
      context: ../frontend
    ports:
      - "4200:80"
    depends_on:
      - planning-poker-backend
