quarkus.rest-client.gitlab-api.url=${GITLAB_URL:http://localhost:8080}
gitlab.token=${GITLAB_TOKEN:}
mp.jwt.verify.publickey.location=${JWT_PUBLIC_KEY_LOCATION:file:/run/secrets/jwt-public-key.pem}
mp.jwt.verify.issuer=planning-poker-backend
smallrye.jwt.sign.key.location=${JWT_PRIVATE_KEY_LOCATION:file:/run/secrets/jwt-private-key.pem}
smallrye.jwt.new-token.issuer=planning-poker-backend
smallrye.jwt.new-token.lifespan=3600
quarkus.smallrye-openapi.store-schema-directory=target/openapi
quarkus.smallrye-openapi.store-schema-file-name=planning-poker-api
quarkus.swagger-ui.always-include=true
%prod.quarkus.swagger-ui.urls.default=/api/q/openapi
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:4200,http://69.62.113.205:4200
quarkus.http.cors.methods=GET,POST,PUT,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type
