quarkus.rest-client.gitlab-api.url=${GITLAB_URL:http://localhost:8080}
gitlab.token=${GITLAB_TOKEN:}
mp.jwt.verify.publickey.location=${JWT_PUBLIC_KEY_LOCATION:file:/run/secrets/jwt-public-key.pem}
mp.jwt.verify.issuer=planning-poker-backend
smallrye.jwt.sign.key.location=${JWT_PRIVATE_KEY_LOCATION:file:/run/secrets/jwt-private-key.pem}
smallrye.jwt.new-token.issuer=planning-poker-backend
smallrye.jwt.new-token.lifespan=3600
quarkus.smallrye-openapi.store-schema-directory=target/openapi
quarkus.smallrye-openapi.store-schema-file-name=planning-poker-api
