quarkus.rest-client.gitlab-api.url=${GITLAB_URL:http://localhost:8080}
gitlab.token=${GITLAB_TOKEN:}
quarkus.smallrye-openapi.store-schema-directory=target/openapi
quarkus.smallrye-openapi.store-schema-file-name=planning-poker-api
